### ISSUE TITLE
Canonicalize `tosa.resize` operation

### ISSUE THREAD

**Issue by dcaballe** [iree-org/iree#10412]
The current implementation of `tosa.resize` is not vectorizable as it generates a complex `tensor.extract` operation. However, it looks like some `tosa.resize` ops can be canonicalize away. This issue is to request the implementation of the missing canonicalization patterns. Please, take a look at https://github.com/iree-org/iree/issues/10313 for context.

**Comment by rsuderman** [comment]
`tosa.resize` is landing a change relatively soon so once the new version is checked in we can find the no-op canonicalizer. We should try to identify both the cases for nearest-neighbour and bilinear, as nearest neighbour can be a little trickier to identify all no-op cases.

**Comment by rsuderman** [comment]
This should be fixed now.

**Comment by dcaballe** [comment]
I'm still getting this error with the to-be-landed integrate (https://github.com/iree-org/iree/pull/10781):

```
/usr/local/google/home/diegocaballero/sandbox/models/deeplabv3/deeplabv3.mlir:229:12: error: 'tosa.resize' op requires attribute 'border'
    %226 = "tosa.resize"(%225) {mode = "BILINEAR", offset = [0, 0], offset_fp = [0.000000e+00 : f32, 0.000000e+00 : f32], output_size = [33, 33], shift = 0 : i32, stride = [0, 0], stride_fp = [0.000000e+00 : f32, 0.000000e+00 : f32]} : (tensor<1x1x1x256xf32>) -> tensor<1x33x33x256xf32>
```

I'm not sure if it's related to this canonicalization or some of the new changes on the `tosa.resize` op but I can't test it... Any idea?

**Comment by dcaballe** [comment]
I'm still seeing the `tosa.resize` in deeplabv3 after:
```
commit bba48dfe4ac4be72d74bb33e646d0b3984eeded1
Author: Rob Suderman <suderman@google.com>
Date:   Wed Oct 5 16:28:19 2022 -0700

    [mlir][tosa] tosa.resize canonicalizer for trivial noop
    
    If the scaling factor is by 1 with no offset or border, then the
    resize is a no-op.
    
    Reviewed By: dcaballe
    
    Differential Revision: https://reviews.llvm.org/D135329
```

Did you check if your patch is optimizing the test case provided in https://github.com/iree-org/iree/issues/10313? That would be helpful.

**Comment by rsuderman** [comment]
Verified that it removes the following case:
```
    %233 = "tosa.resize"(%232) {border = [0, 0], mode = "BILINEAR", offset = [0, 0], scale = [2, 2, 2, 2]} : (tensor<1x33x33x21xf32>) -> tensor<1x33x33x21xf32>
```
