### ISSUE TITLE
WebGPU compilation errors: "function parameter of pointer type cannot be in 'storage' address space"

### ISSUE THREAD

**Issue by ScottTodd** [iree-org/iree#10906]
### What happened?

Several of our tests are failing to compile using the WebGPU compiler target, during compilation from SPIR-V to WGSL using Tint.

From [`tests/e2e/xla_ops/`](https://github.com/iree-org/iree/tree/main/tests/e2e/xla_ops):
  * clamp.mlir
  * compare.mlir
  * convert.mlir
  * finite.mlir
  * maximum.mlir
  * minimum.mlir

From [`tests/e2e/tosa_ops/`](https://github.com/iree-org/iree/tree/main/tests/e2e/tosa_ops):
  * equal.mlir
  * greater.mlir
  * greater_equal.mlir
  * max_pool.mlir
  * table.mlir

The error message from Tint is:
```
Tint reported 1 error(s) for a SPIR-V program, see diagnostics:
error: function parameter of pointer type cannot be in 'storage' address space
```

### Steps to reproduce your issue

Either add a test suite to `tests/e2e/xla_ops/` or `tests/e2e/tosa_ops/` with
```cmake
  TARGET_BACKEND
    "webgpu"
  # Only test compilation for now, the WebGPU driver is not stable/tested yet.
  # DRIVER
  #   "webgpu"
```

OR just run the compiler on one of those files directly, e.g.
```shell
iree-compile --iree-hal-target-backends=webgpu \
  --iree-input-type=mhlo tests/e2e/xla_ops/clamp.mlir \
  --iree-hal-dump-executable-sources-to=/tmp/iree/webgpu_clamp/ \
  --iree-hal-dump-executable-intermediates-to=/tmp/iree/webgpu_clamp/ \
  --iree-hal-dump-executable-binaries-to=/tmp/iree/webgpu_clamp/ \
  -o /dev/null \
```

### Version information

Tip of tree, https://github.com/iree-org/iree/commit/29b1e8832fd87080716545b0337276e0b3aed636

### Additional context

At least some of these tests successfully compile when they are modified to only use i32 and f32 types, and not i8 or i16.

This gist has the .spvasm that IREE feeds to Tint for i8 (fails) and for i32 (succeeds): https://gist.github.com/ScottTodd/c01f1591d8ff2ed38896adcd609ddd65

**Comment by antiagainst** [comment]
From @dneto0: https://dawn-review.googlesource.com/c/dawn/+/109820 should fix this.

**Comment by ScottTodd** [comment]
I'm still seeing this issue after updating Tint. I've only seen it affect unit tests (and not full programs) so far though.

**Comment by dneto0** [comment]
> I'm still seeing this issue after updating Tint. I've only seen it affect unit tests (and not full programs) so far though.

Currently WGSL does not allow passing pointer-to-storage-buffer or pointer-to-uniform-buffer into user-declared helper functions.

But this is planned as an enhancement "soon", because @ben-clayton worked out a transform that would lower more general pointer parameters to something we could compile to all backends.  
See https://github.com/gpuweb/gpuweb/issues/3546
