### ISSUE TITLE
[Regression] Large models taking more than an hour to build

### ISSUE THREAD

**Issue by mariecwhite** [iree-org/iree#14067]
### What happened?

Between f3d0369 and 967ab3b, [Benchmark Large](https://github.com/openxla/iree/actions/workflows/benchmark_large.yml) workflow started timing out. Several JAX models are taking more than an hour to build on CUDA. These models took at most 2 minutes to build.

### Steps to reproduce your issue

Download any one of:
- https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/T5_LARGE/batch_16/stablehlo.mlirbc
- https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/T5_LARGE/batch_24/stablehlo.mlirbc
- https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/T5_LARGE/batch_32/stablehlo.mlirbc
- https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/T5_LARGE/batch_48/stablehlo.mlirbc

Compile:
```
iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 <path to mlirbc> -o /tmp/module.vmfb
```

### Version information

Started failing between f3d0369 and 967ab3b.

**Comment by mariecwhite** [comment]
I'm going to start bisecting to find the culprit commit.

**Comment by ScottTodd** [comment]
https://github.com/openxla/iree/blob/main/docs/developers/debugging/compile_time_regressions.md has a script you can run to bisect.

**Comment by ScottTodd** [comment]
BTW, if you have a different workflow or script for culprit finding, documentation contributions are quite welcome :)

**Comment by mariecwhite** [comment]
I was going to run the Benchmark Large workflow at different commits and see which times out :)

**Comment by ScottTodd** [comment]
I'll race you :D

Just started a bisect run using the script and the commit range mentioned above. We'll see how my ccache performs.

**Comment by mariecwhite** [comment]
Sounds good! I have 3 workflows running on commits that look to be the culprits.

**Comment by ScottTodd** [comment]
My bisect points to https://github.com/openxla/iree/commit/b3a1ac9e8592f911195fa829ca1b13a280da4c73

Looks like compilation of this executable got much slower:

```mlir
hal.executable public @main_dispatch_394 {
  hal.executable.variant public @cuda_nvptx_fb, target = <"cuda", "cuda-nvptx-fb", {target_arch = "sm_80"}> {
    hal.executable.export public @main_dispatch_394_generic_16x16x512x512_i32xi32xi32xf32 ordinal(0) layout(#hal.pipeline.layout<push_constants = 0, sets = [<0, bindings = [<0, storage_buffer, ReadOnly>, <1, storage_buffer, ReadOnly>, <2, storage_buffer>]>]>) {
    ^bb0(%arg0: !hal.device):
      %x, %y, %z = flow.dispatch.workgroup_count_from_slice 
      hal.return %x, %y, %z : index, index, index
    }
    builtin.module {
      func.func @main_dispatch_394_generic_16x16x512x512_i32xi32xi32xf32() {
        %c1598324736 = arith.constant 1598324736 : index
        %c33554432 = arith.constant 33554432 : index
        %c167772160 = arith.constant 167772160 : index
        %c234883072 = arith.constant 234883072 : index
        %c0_i32 = arith.constant 0 : i32
        %cst = arith.constant 1.600000e+01 : f32
        %cst_0 = arith.constant 2.07944155 : f32
        %cst_1 = arith.constant 3.100000e+01 : f32
        %c16_i32 = arith.constant 16 : i32
        %cst_2 = arith.constant 0.000000e+00 : f32
        %c32_i32 = arith.constant 32 : i32
        %false = arith.constant false
        %cst_3 = arith.constant -3.40282347E+38 : f32
        %c31_i32 = arith.constant 31 : i32
        %cst_4 = arith.constant 0x7FC00000 : f32
        %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c1598324736) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<32x16xf32>>
        %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c33554432) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512x512xi32>>
        %2 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c167772160) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<512xi32>>
        %3 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c234883072) : !flow.dispatch.tensor<writeonly:tensor<16x16x512x512xf32>>
        %4 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [32, 16], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<32x16xf32>> -> tensor<32x16xf32>
        %5 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [512, 512], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<512x512xi32>> -> tensor<512x512xi32>
        %6 = flow.dispatch.tensor.load %2, offsets = [0], sizes = [512], strides = [1] : !flow.dispatch.tensor<readonly:tensor<512xi32>> -> tensor<512xi32>
        %7 = tensor.empty() : tensor<16x16x512x512xf32>
        %8 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3) -> (d2, d3)>, affine_map<(d0, d1, d2, d3) -> (d2)>, affine_map<(d0, d1, d2, d3) -> (d3)>, affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>], iterator_types = ["parallel", "parallel", "parallel", "parallel"]} ins(%5, %6, %6 : tensor<512x512xi32>, tensor<512xi32>, tensor<512xi32>) outs(%7 : tensor<16x16x512x512xf32>) {
        ^bb0(%in: i32, %in_5: i32, %in_6: i32, %out: f32):
          %9 = arith.cmpi sge, %in_5, %in_6 : i32
          %10 = arith.minsi %in, %c0_i32 : i32
          %11 = arith.subi %c0_i32, %10 : i32
          %12 = arith.sitofp %11 : i32 to f32
          %13 = arith.divf %12, %cst : f32
          %14 = math.log %13 : f32
          %15 = arith.divf %14, %cst_0 : f32
          %16 = arith.mulf %15, %cst : f32
          %17 = arith.addf %16, %cst : f32
          %18 = arith.minf %17, %cst_1 : f32
          %19 = arith.cmpi slt, %11, %c16_i32 : i32
          %20 = arith.select %19, %12, %18 : f32
          %21 = arith.addf %20, %cst_2 : f32
          %22 = arith.fptosi %21 : f32 to i32
          %23 = arith.addi %22, %c32_i32 : i32
          %24 = arith.cmpi slt, %22, %c0_i32 : i32
          %25 = arith.select %24, %23, %22 : i32
          %26 = linalg.index 1 : index
          %27 = arith.index_cast %25 : i32 to index
          %extracted = tensor.extract %4[%27, %26] : tensor<32x16xf32>
          %28 = arith.cmpi ugt, %9, %false : i1
          %29 = arith.select %28, %cst_2, %cst_3 : f32
          %30 = arith.cmpi sle, %25, %c31_i32 : i32
          %31 = arith.cmpi sge, %25, %c0_i32 : i32
          %32 = arith.andi %31, %30 : i1
          %33 = arith.select %32, %extracted, %cst_4 : f32
          %34 = arith.addf %33, %29 : f32
          linalg.yield %34 : f32
        } -> tensor<16x16x512x512xf32>
        flow.dispatch.tensor.store %8, %3, offsets = [0, 0, 0, 0], sizes = [16, 16, 512, 512], strides = [1, 1, 1, 1] : tensor<16x16x512x512xf32> -> !flow.dispatch.tensor<writeonly:tensor<16x16x512x512xf32>>
        return
      }
    }
  }
}
```

**Comment by ScottTodd** [comment]
Slow in executable serialization (LLVM codegen for CUDA). IR just before the slowness doesn't look _that_ strange to me: https://gist.github.com/ScottTodd/f795f62b23ba2df1d51d785b4dbbb8eb

Trace instrumentation: 
![image](https://github.com/openxla/iree/assets/4010439/2dc3ff59-3aeb-4396-aea8-08058a3d2d72)

Trace sampling: 
![image](https://github.com/openxla/iree/assets/4010439/5cbe50d5-e3e8-492e-8691-510f7e302424)
![image](https://github.com/openxla/iree/assets/4010439/8db84b1a-c668-40d8-b25e-c3241a8cd54a)

**Comment by mariecwhite** [comment]
Nice bisecting! I can also confirm that https://github.com/openxla/iree/commit/b3a1ac9e8592f911195fa829ca1b13a280da4c73 is taking longer than expected.

**Comment by ScottTodd** [comment]
Here are a few callstacks where time is being spent (just paused in a debugger at random times):

```c++
llvm::TargetLoweringBase::getTypeConversion(llvm::LLVMContext&, llvm::EVT) const (iree/third_party/llvm-project/llvm/lib/CodeGen/TargetLoweringBase.cpp:981)
llvm::TargetLoweringBase::getTypeAction(llvm::LLVMContext&, llvm::EVT) const (iree/third_party/llvm-project/llvm/include/llvm/CodeGen/TargetLowering.h:1019)
llvm::SelectionDAGBuilder::visitSelect(llvm::User const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:3409)
llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1190)
llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:691)
llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1700)
llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:482)
llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (iree/third_party/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:91)
llvm::FPPassManager::runOnFunction(llvm::Function&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1435)
llvm::FPPassManager::runOnModule(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1481)
(anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1550)
llvm::legacy::PassManagerImpl::run(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535)
mlir::iree_compiler::IREE::HAL::translateModuleToISA[abi:cxx11](llvm::Module&, llvm::TargetMachine&) (iree/compiler/plugins/target/CUDA/CUDATarget.cpp:261)
mlir::iree_compiler::IREE::HAL::CUDATargetBackend::serializeExecutable(mlir::iree_compiler::IREE::HAL::TargetBackend::SerializationOptions const&, mlir::iree_compiler::IREE::HAL::ExecutableVariantOp, mlir::OpBuilder&) (iree/compiler/plugins/target/CUDA/CUDATarget.cpp:584)
mlir::iree_compiler::IREE::HAL::SerializeTargetExecutablesPass::runOnOperation() (iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/SerializeExecutables.cpp:98)
mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7::operator()() const (iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:482)
void llvm::function_ref<void ()>::callback_fn<mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7>(long) (iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45)
llvm::function_ref<void ()>::operator()() const (iree/third_party/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68)
void mlir::MLIRContext::executeAction<mlir::PassExecutionAction, mlir::Pass&>(llvm::function_ref<void ()>, llvm::ArrayRef<mlir::IRUnit>, mlir::Pass&) (iree/third_party/llvm-project/mlir/include/mlir/IR/MLIRContext.h:275)
mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:476)
```

```c++
llvm::MVT::getVectorVT(llvm::MVT, unsigned int) (iree-build/llvm-project/include/llvm/CodeGen/GenVT.inc:268)
llvm::MVT::getVectorVT(llvm::MVT, llvm::ElementCount) (iree/third_party/llvm-project/llvm/include/llvm/CodeGen/MachineValueType.h:477)
llvm::EVT::getVectorVT(llvm::LLVMContext&, llvm::EVT, llvm::ElementCount) (iree/third_party/llvm-project/llvm/include/llvm/CodeGen/ValueTypes.h:84)
llvm::EVT::getHalfNumVectorElementsVT(llvm::LLVMContext&) const (iree/third_party/llvm-project/llvm/include/llvm/CodeGen/ValueTypes.h:435)
llvm::TargetLoweringBase::getTypeConversion(llvm::LLVMContext&, llvm::EVT) const (iree/third_party/llvm-project/llvm/lib/CodeGen/TargetLoweringBase.cpp:996)
llvm::TargetLoweringBase::getTypeAction(llvm::LLVMContext&, llvm::EVT) const (iree/third_party/llvm-project/llvm/include/llvm/CodeGen/TargetLowering.h:1019)
llvm::SelectionDAGBuilder::visitSelect(llvm::User const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:3409)
llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:1190)
llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, llvm::ilist_iterator<llvm::ilist_detail::node_options<llvm::Instruction, false, false, void>, false, true>, bool&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:691)
llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1700)
llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (iree/third_party/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:482)
llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (iree/third_party/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:91)
llvm::FPPassManager::runOnFunction(llvm::Function&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1435)
llvm::FPPassManager::runOnModule(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1481)
(anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1550)
llvm::legacy::PassManagerImpl::run(llvm::Module&) (iree/third_party/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:535)
mlir::iree_compiler::IREE::HAL::translateModuleToISA[abi:cxx11](llvm::Module&, llvm::TargetMachine&) (iree/compiler/plugins/target/CUDA/CUDATarget.cpp:261)
mlir::iree_compiler::IREE::HAL::CUDATargetBackend::serializeExecutable(mlir::iree_compiler::IREE::HAL::TargetBackend::SerializationOptions const&, mlir::iree_compiler::IREE::HAL::ExecutableVariantOp, mlir::OpBuilder&) (iree/compiler/plugins/target/CUDA/CUDATarget.cpp:584)
mlir::iree_compiler::IREE::HAL::SerializeTargetExecutablesPass::runOnOperation() (iree/compiler/src/iree/compiler/Dialect/HAL/Transforms/SerializeExecutables.cpp:98)
mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int)::$_7::operator()() const (iree/third_party/llvm-project/mlir/lib/Pass/Pass.cpp:482)
```

**Comment by ScottTodd** [comment]
Hmmmm.... the IR being fed into `iree-hal-serialize-target-executables` is identical at https://github.com/openxla/iree/commit/b3a1ac9e8592f911195fa829ca1b13a280da4c73 (culprit) and it's parent https://github.com/openxla/iree/commit/1b8e95c3a707a98476e7f5cf4e6d10c91aa3cab0. Maybe this is a regression in LLVM codegen? Infinite loop / no termination condition?

The parent commit serializes in 15ms:
![image](https://github.com/openxla/iree/assets/4010439/dcddf5de-2213-489e-ba37-5a5353ab3205)

**Comment by ScottTodd** [comment]
Bisecting within llvm-project is normally tricky, though there aren't many IREE code changes in the culprit, so it would be possible with some effort.

I scanned through the commits and found https://github.com/llvm/llvm-project/commit/2fe2a6d4b8a4647e49d69a5ff7161946aeb7cee1 as one idea to test...

**Comment by ScottTodd** [comment]
Maybe we could extract a reproducer to use with `llvm::legacy::PassManagerImpl::run(llvm::Module&)` and test purely with upstream LLVM code (not in the IREE repo / with `iree-compile`).

**Comment by ScottTodd** [comment]
I think I've done what I can to triage this, probably need someone more familiar with codegen (LLVM for CUDA) to dig in deeper.

**Comment by ScottTodd** [comment]
(A simpler IREE repro is to take the IR from https://github.com/openxla/iree/issues/14067#issuecomment-1588133415 and compile with `--compile-mode=hal-executable --iree-hal-target-backends=cuda --iree-hal-cuda-llvm-target-arch=sm_80`)

**Comment by mariecwhite** [comment]
This is also causing pjrt to hang. See https://github.com/openxla/openxla-pjrt-plugin/issues/141#

**Comment by dcaballe** [comment]
Could you please verify that this is fixed after the last integrate? All the models above are taking just a few seconds to compile :)

**Comment by mariecwhite** [comment]
Sure, I've started a run based on head: https://github.com/openxla/iree/actions/runs/5263690485

**Comment by mariecwhite** [comment]
It's not fixed after the latest integrate. What usually takes 18 mins to build is already taking 1h 20 min and will most likely time out.

**Comment by dcaballe** [comment]
Could anybody help me repro? I must be missing something...

IREE commit:
```
commit 8af37c070b7a65cd324ad5e06eb4455084be28e8 (HEAD -> main, origin/main, origin/HEAD)
Author: Lei Zhang <antiagainst@google.com>
Date:   Wed Jun 14 13:47:06 2023 -0400

    [ci] Update Xcode command line tools path on x86_64 macOS runners (#14108)
    
    This fixes the breakage on x86_64 macOS runners.
```

```
> wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/T5_LARGE/batch_48/stablehlo.mlirbc
> time iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo 
--iree-hal-cuda-llvm-target-arch=sm_80 stablehlo.mlirbc -o module.vmfb

real    0m13.205s
user    0m15.586s
sys     0m7.123s
```

**Comment by pzread** [comment]
I rebuilt the large benchmark set on eb26576d8190600f4c0556e8594469896348a9f5 and confirmed that T5 Large models listed in the issue can be built now (log: https://github.com/openxla/iree/actions/runs/5272859303/jobs/9535738445)

But the Bert Large still failed to build (taking too long)... So the large benchmark workflow is still failing

To reproduce:
```
wget https://storage.googleapis.com/iree-model-artifacts/jax/jax_models_0.4.10_1684396752/BERT_LARGE/batch_24/stablehlo.mlirbc
iree-compile --output-format=vm-bytecode --mlir-print-op-on-diagnostic=false --iree-hal-target-backends=cuda --iree-input-type=stablehlo --iree-hal-cuda-llvm-target-arch=sm_80 -o module.vmfb ./stablehlo.mlirbc
```

These batch sizes failed to build: 16, 24, 32, 48, 64, 512, 1024, 1280

@mariecwhite would you mind double check on the BERT Large models and maybe open a new issue?

**Comment by mariecwhite** [comment]
The original bug referred to both T5 Large and BERT models. If @ScottTodd can still reproduce it in a dispatch, I'm guessing that dispatch is no longer present in T5 but in BERT. @dcaballe do you mind reproducing with the BERT model that @pzread included in his last comment?

**Comment by dcaballe** [comment]
Found the culprit. We can land this in the meantime if this is issue is a blocker: https://github.com/openxla/iree/pull/14125
Sending a repro to LLVM review.

**Comment by dcaballe** [comment]
The problematic PR had been reverted already but we won't get it until it's integrated into stablehlo.
https://reviews.llvm.org/D152317

**Comment by mariecwhite** [comment]
Fixed. Thanks Diego, Scott and Che-Yu!

**Comment by ScottTodd** [comment]
Nice find! From that review, here's an upstream issue with the same symptoms: https://github.com/llvm/llvm-project/issues/63294
