### ISSUE TITLE
powf is giving NAN for certain set of values in the GPT2Test.test_compile_tflite test

### ISSUE THREAD

**Issue by bviyer** [iree-org/iree#14763]
### What happened?

The test `GPT2Test.test_compile_tflite` is failing with the following issues:

I0809 23:16:48.301630 140460146829120 test_util.py:96] Max error (0): nan
284I0809 23:16:48.303588 140460146829120 test_util.py:96] Max error (1): nan
285I0809 23:16:48.303945 140460146829120 test_util.py:96] Max error (2): nan
286I0809 23:16:48.304274 140460146829120 test_util.py:96] Max error (3): nan
287I0809 23:16:48.304575 140460146829120 test_util.py:96] Max error (4): nan
288I0809 23:16:48.304873 140460146829120 test_util.py:96] Max error (5): 0.000005
289I0809 23:16:48.305178 140460146829120 test_util.py:96] Max error (6): nan
290I0809 23:16:48.305528 140460146829120 test_util.py:96] Max error (7): nan
291I0809 23:16:48.305834 140460146829120 test_util.py:96] Max error (8): nan
292I0809 23:16:48.306143 140460146829120 test_util.py:96] Max error (9): nan
293I0809 23:16:48.306478 140460146829120 test_util.py:96] Max error (10): nan
294I0809 23:16:48.306790 140460146829120 test_util.py:96] Max error (11): nan
295I0809 23:16:48.307113 140460146829120 test_util.py:96] Max error (12): nan

I have a hunch - need to dig further to confirm - that this is due to an unhandled issue in the Powf decomposition in mlir/lib/Dialect/Math/Transforms/ExpandPatterns.cpp

**Comment by bviyer** [comment]
I tried to reproduce this but I am not able to (See test 16 of 21). Here is the output I am seeing:
```
(.venv) $ third_party/llvm-project/llvm/utils/lit/lit.py -v integrations/tensorflow/test --max-time 1800 -D FEATURES=vulkan,vmvx
-- Testing: 21 tests, 21 workers --
UNSUPPORTED: TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_mobilebert_tf2_quant.run (1 of 21)
PASS: TENSORFLOW_TESTS :: iree_tf_tests/llvmcpu__simple_arithmetic.run (2 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_mobilenet_v1.run (3 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_person_detect.run (4 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_mobilenet_v1.run (5 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/cartoon_gan.run (6 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_resnet_50_int8.run (7 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_posenet_i8.run (8 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_mobilenet_v3-large_uint8.run (9 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/person_detect.run (10 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/mnasnet.run (11 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_mobilenet_v3-large_uint8.run (12 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/east_text_detector.run (13 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_resnet_50_int8.run (14 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/mobilenet_v3.run (15 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/gpt2.run (16 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_resnet_50_int8.run (17 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/vulkan_mobilebert_tf2_quant.run (18 of 21)
XFAIL: TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_posenet_i8.run (19 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/llvmcpu_mobilenet_v3-large_uint8.run (20 of 21)
PASS: TENSORFLOW_TESTS :: iree_tfl_tests/vmvx_mobilebert_tf2_quant.run (21 of 21)

Testing Time: 156.46s
  Unsupported      :  1
  Passed           : 13
  Expectedly Failed:  7

```

Here are the instructions I followed to build IREE (including python bindings): https://openxla.github.io/iree/building-from-source/getting-started/

My IREE HEAD is pointed to: 3e31d4c5650598351e9976dc3e1f5dc427ce7b45

**Comment by dcaballe** [comment]
Hey @bviyer, if the pow expansion is returning NaN for integer pow, perhaps the expansion should bail out if the type is integer for now? Is the current expansion ready to handle integer or are they converted to 32 or 64-bit floating point?

**Comment by bviyer** [comment]
This commit should fix this issue: https://reviews.llvm.org/rGf66e4bd67adf0b0aaecd94154c38f02253bf7190

@dcaballe Please let me know if we can close this bug.

**Comment by dcaballe** [comment]
I think we still have some failures on GPU here: https://github.com/openxla/iree/actions/runs/5979666135/job/16224775842?pr=14614. I see:
```
/work/runtime/src/iree/hal/drivers/cuda/native_executable.c:102: INTERNAL; CUDA driver error 'CUDA_ERROR_INVALID_PTX' (218): a PTX JIT compilation failed; while invoking native function hal.executable.create; while calling import; 
```

We need to understand if it's a problem of the new powf lowering or something else since the next integrate might get stuck when integrating your commit. I just rebased the PR to see if the problem is gone with the last integrate.

**Comment by bviyer** [comment]
@dcaballe Can we close this as well?

**Comment by bviyer** [comment]
@dcaballe I am closing this for now. Please let me know if there is issues and I can reopen it and look into it.
