### ISSUE TITLE
TF integrations Python + Vulkan failures

### ISSUE THREAD

**Issue by GMNGeoffrey** [iree-org/iree#9936]
### Issue body

In #9927, I'm consistently hitting the following error in 25 vulkan TF integrations tests

> python3: /home/runner/actions-runner/_work/iree/iree/third_party/vulkan_memory_allocator/include/vk_mem_alloc.h:11939: void VmaDeviceMemoryBlock::Destroy(VmaAllocator): Assertion `m_pMetadata->IsEmpty() && "Some allocations were not freed before destruction of this memory block!"' failed.

This is the same error message as #3381, but @stellaraccident suggested it was probably a different issue. Odd about this issue is that it happens consistently on the GitHub actions runner, but wasn't happening on Kokoro at all. I've tried reducing test parallelism to ensure this isn't some issue of competing for resources (one difference with the new machines is that they have more cores and #9905 hit this issue), but that did not help.

For now, I'm going to disable the Vulkan tests in this job, but this will block #9855.

These are the failing tests:

```
iree_tf_tests/layers/vulkan__Add.run
iree_tf_tests/layers/vulkan__AdditiveAttention.run
iree_tf_tests/layers/vulkan__Attention.run
iree_tf_tests/layers/vulkan__Average.run
iree_tf_tests/layers/vulkan__Concatenate.run
iree_tf_tests/layers/vulkan__Dot.run
iree_tf_tests/layers/vulkan__Maximum.run
iree_tf_tests/layers/vulkan__Minimum.run
iree_tf_tests/layers/vulkan__MultiHeadAttention.run
iree_tf_tests/layers/vulkan__Multiply.run
iree_tf_tests/layers/vulkan__Subtract.run
iree_tf_tests/layers/vulkan__dynamic_dims_Add.run
iree_tf_tests/layers/vulkan__dynamic_dims_Average.run
iree_tf_tests/layers/vulkan__dynamic_dims_Maximum.run
iree_tf_tests/layers/vulkan__dynamic_dims_Minimum.run
iree_tf_tests/layers/vulkan__dynamic_dims_Multiply.run
iree_tf_tests/layers/vulkan__dynamic_dims_Subtract.run
iree_tf_tests/layers/vulkan__full_api_AdditiveAttention.run
iree_tf_tests/layers/vulkan__full_api_Attention.run
iree_tf_tests/layers/vulkan__full_api_Concatenate.run
iree_tf_tests/math/vulkan__accumulate_n.run
iree_tf_tests/math/vulkan__add_n.run
iree_tf_tests/math/vulkan__dynamic_dim_polyval.run
iree_tf_tests/math/vulkan__polyval.run
iree_tf_tests/uncategorized/vulkan__pytree.run
```

Full logs: https://gist.githubusercontent.com/GMNGeoffrey/6e1ca63782858a2d9ee36157351032a1/raw/e7454d9b4a2fbc8dbdd65630b8bd5c145fdeffdd/logs.txt

**Comment by ScottTodd** [comment]
What's the Vulkan environment like on these runners? Vulkan SDK version, GPU driver version, physical GPU vs SwiftShader, etc.

**Comment by GMNGeoffrey** [comment]
It's all in the swiftshader-frontends docker container

**Comment by GMNGeoffrey** [comment]
Seems like @stellaraccident already has a draft PR for fixing this

**Comment by stellaraccident** [comment]
Didn't mean to have this auto-close. I haven't verified but do expect that the root cause is fixed. Let me know if not.

**Comment by GMNGeoffrey** [comment]
I'm still seeing the same failures in https://github.com/iree-org/iree/pull/9954

**Comment by stellaraccident** [comment]
Boo. What do I do to test this?

**Comment by GMNGeoffrey** [comment]
Well there's the really slow way of iterating via GitHub actions 😆 I think I actually got the same errors on my 96-core workstation, but I can also point you at a VM with the same config as the CI
